import DbhLogo from "@/assets/svgs/quizzes/dbhLogo.svg";
import Rdr2Logo from "@/assets/svgs/quizzes/rdr2Logo.svg";
import TlouLogo from "@/assets/svgs/quizzes/tlouLogo.svg";

export const cards = [
  {
    id: "1",
    svg: <DbhLogo width="100%" height="100%" />,
    title: "Detroit Become Human",
    company: "Quantic Dream",
    progress: 0.95,
    rewards: 190,
    total: 200,
    levels: [
      {
        name: "easy",
        questions: 10,
        completedQuestions: 8,
        rewards: 32,
        total: 50,
      },
      {
        name: "normal",
        questions: 10,
        completedQuestions: 9,
        rewards: 44,
        total: 50,
      },
      {
        name: "hard",
        questions: 10,
        completedQuestions: 6,
        rewards: 28,
        total: 50,
      },
      {
        name: "extreme",
        questions: 10,
        completedQuestions: 3,
        rewards: 12,
        total: 50,
      },
    ],
  },
  {
    id: "2",
    svg: <Rdr2Logo width="100%" height="100%" />,
    title: "Red Dead Redemption II",
    company: "Rockstar Games",
    progress: 0.7,
    rewards: 200,
    total: 300,
    levels: [
      {
        name: "easy",
        questions: 10,
        completedQuestions: 8,
        rewards: 32,
        total: 50,
      },
      {
        name: "normal",
        questions: 10,
        completedQuestions: 9,
        rewards: 44,
        total: 50,
      },
      {
        name: "hard",
        questions: 10,
        completedQuestions: 6,
        rewards: 28,
        total: 50,
      },
      {
        name: "extreme",
        questions: 10,
        completedQuestions: 3,
        rewards: 12,
        total: 50,
      },
    ],
  },
  {
    id: "3",
    svg: <TlouLogo width="100%" height="100%" />,
    title: "The Last Of Us",
    company: "Naughty Dog",
    progress: 0.87,
    rewards: 150,
    total: 250,
    levels: [
      {
        name: "easy",
        questions: 10,
        completedQuestions: 8,
        rewards: 32,
        total: 50,
      },
      {
        name: "normal",
        questions: 10,
        completedQuestions: 9,
        rewards: 44,
        total: 50,
      },
      {
        name: "hard",
        questions: 10,
        completedQuestions: 6,
        rewards: 28,
        total: 50,
      },
      {
        name: "extreme",
        questions: 10,
        completedQuestions: 3,
        rewards: 12,
        total: 50,
      },
    ],
  },
  {
    id: "4",
    svg: <DbhLogo width="100%" height="100%" />,
    title: "Detroit Become Human",
    company: "Quantic Dream",
    progress: 0.35,
    rewards: 100,
    total: 200,
    levels: [
      {
        name: "easy",
        questions: 10,
        completedQuestions: 8,
        rewards: 32,
        total: 50,
      },
      {
        name: "normal",
        questions: 10,
        completedQuestions: 9,
        rewards: 44,
        total: 50,
      },
      {
        name: "hard",
        questions: 10,
        completedQuestions: 6,
        rewards: 28,
        total: 50,
      },
      {
        name: "extreme",
        questions: 10,
        completedQuestions: 3,
        rewards: 12,
        total: 50,
      },
    ],
  },
  {
    id: "5",
    svg: <Rdr2Logo width="100%" height="100%" />,
    title: "Red Dead Redemption II",
    company: "Rockstar Games",
    progress: 0.7,
    rewards: 200,
    total: 300,
    levels: [
      {
        name: "easy",
        questions: 10,
        completedQuestions: 8,
        rewards: 32,
        total: 50,
      },
      {
        name: "normal",
        questions: 10,
        completedQuestions: 9,
        rewards: 44,
        total: 50,
      },
      {
        name: "hard",
        questions: 10,
        completedQuestions: 6,
        rewards: 28,
        total: 50,
      },
      {
        name: "extreme",
        questions: 10,
        completedQuestions: 3,
        rewards: 12,
        total: 50,
      },
    ],
  },
  {
    id: "6",
    svg: <TlouLogo width="100%" height="100%" />,
    title: "The Last Of Us",
    company: "Naughty Dog",
    progress: 0.87,
    rewards: 150,
    total: 250,
    levels: [
      {
        name: "easy",
        questions: 10,
        completedQuestions: 8,
        rewards: 32,
        total: 50,
      },
      {
        name: "normal",
        questions: 10,
        completedQuestions: 9,
        rewards: 44,
        total: 50,
      },
      {
        name: "hard",
        questions: 10,
        completedQuestions: 6,
        rewards: 28,
        total: 50,
      },
      {
        name: "extreme",
        questions: 10,
        completedQuestions: 3,
        rewards: 12,
        total: 50,
      },
    ],
  },
];
